language: r
cache: packages

r:
  - release
  - devel

sudo: false

addons:
  apt:
    packages:
      - qpdf

r_binary_packages:
  - testthat
  - vegan
  - Rcpp
  - crayon
  - lazyeval
  - jsonlite
  - htmltools

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

r_build_args: " --compact-vignettes=gs+qpdf"
r_check_args: " --as-cran"

notifications:
  email:
    on_success: change
    on_failure: always
