test_that("fitted() works & with default args", {
  data(beetles, plants)
  bp.sym <- coca(beetles ~ ., data = plants, method = "symmetric", quiet = TRUE)
  expect_silent(ff <- fitted(bp.sym))
  expect_s3_class(ff, "fitted.symcoca")
  expect_named(ff, c("Y", "X", "nam.dat"))
  expect_length(ff$nam.dat, 2L)
  expect_output(print(ff), regexp = "Fitted values for:")
})

test_that("fitted() works for a single 'which'", {
  data(beetles, plants)
  bp.sym <- coca(beetles ~ ., data = plants, method = "symmetric", quiet = TRUE)
  expect_silent(ff <- fitted(bp.sym, which = "response"))
  expect_s3_class(ff, "fitted.symcoca")
  expect_named(ff, c("Y", "nam.dat"))
  expect_length(ff$nam.dat, 1L)
  expect_equal(unname(ff$nam.dat[1]), "beetles")
  expect_output(print(ff), regexp = "Fitted values for: beetles")

  expect_silent(ff <- fitted(bp.sym, which = "predictor"))
  expect_s3_class(ff, "fitted.symcoca")
  expect_named(ff, c("X", "nam.dat"))
  expect_length(ff$nam.dat, 1L)
  expect_equal(unname(ff$nam.dat[1]), "plants")
  expect_output(print(ff), regexp = "Fitted values for: plants")
})
